'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CustomQueryInReportDesigner
    
    Partial Public Class [Default]
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''callbackPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents callbackPanel As Global.DevExpress.Web.ASPxCallbackPanel
        
        '''<summary>
        '''reportDesigner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reportDesigner As Global.DevExpress.XtraReports.Web.ASPxReportDesigner
        
        '''<summary>
        '''callbackValidation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents callbackValidation As Global.DevExpress.Web.ASPxCallback
        
        '''<summary>
        '''popupWizard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents popupWizard As Global.DevExpress.Web.ASPxPopupControl
        
        '''<summary>
        '''PopupControlContentControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl
        
        '''<summary>
        '''frmWizard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmWizard As Global.DevExpress.Web.ASPxFormLayout
        
        '''<summary>
        '''LayoutItemNestedControlContainer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''listBoxDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents listBoxDataSource As Global.DevExpress.Web.ASPxListBox
        
        '''<summary>
        '''LayoutItemNestedControlContainer2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''listBoxQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents listBoxQuery As Global.DevExpress.Web.ASPxListBox
        
        '''<summary>
        '''LayoutItemNestedControlContainer3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''btDataSourceAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btDataSourceAdd As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''LayoutItemNestedControlContainer4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer4 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''btDataSourceEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btDataSourceEdit As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''LayoutItemNestedControlContainer5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer5 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''btDataSourceDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btDataSourceDelete As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btQueryAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btQueryAdd As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btQueryEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btQueryEdit As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btQueryDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btQueryDelete As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''LayoutItemNestedControlContainer6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer6 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''lbWizardError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbWizardError As Global.DevExpress.Web.ASPxLabel
        
        '''<summary>
        '''LayoutItemNestedControlContainer7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LayoutItemNestedControlContainer7 As Global.DevExpress.Web.LayoutItemNestedControlContainer
        
        '''<summary>
        '''btApply control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btApply As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btCancel As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''popupDataSourceEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents popupDataSourceEditor As Global.DevExpress.Web.ASPxPopupControl
        
        '''<summary>
        '''frmDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmDataSource As Global.DevExpress.Web.ASPxFormLayout
        
        '''<summary>
        '''txDataSourceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txDataSourceName As Global.DevExpress.Web.ASPxTextBox
        
        '''<summary>
        '''cbDataSourceConnection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbDataSourceConnection As Global.DevExpress.Web.ASPxComboBox
        
        '''<summary>
        '''lbDataSourceError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbDataSourceError As Global.DevExpress.Web.ASPxLabel
        
        '''<summary>
        '''btDataSourceSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btDataSourceSave As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btDataSourceCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btDataSourceCancel As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''popupQueryEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents popupQueryEditor As Global.DevExpress.Web.ASPxPopupControl
        
        '''<summary>
        '''frmQuery control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmQuery As Global.DevExpress.Web.ASPxFormLayout
        
        '''<summary>
        '''txQueryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txQueryName As Global.DevExpress.Web.ASPxTextBox
        
        '''<summary>
        '''mmQuerySql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mmQuerySql As Global.DevExpress.Web.ASPxMemo
        
        '''<summary>
        '''lbQueryError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbQueryError As Global.DevExpress.Web.ASPxLabel
        
        '''<summary>
        '''btQuerySave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btQuerySave As Global.DevExpress.Web.ASPxButton
        
        '''<summary>
        '''btQueryCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btQueryCancel As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
