'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CustomQueryInReportDesigner


    Partial Public Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' callbackPanel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected callbackPanel As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' reportDesigner control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected reportDesigner As Global.DevExpress.XtraReports.Web.ASPxReportDesigner

        ''' <summary>
        ''' callbackValidation control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected callbackValidation As Global.DevExpress.Web.ASPxCallback

        ''' <summary>
        ''' popupWizard control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected popupWizard As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' PopupControlContentControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl

        ''' <summary>
        ''' frmWizard control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected frmWizard As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' LayoutItemNestedControlContainer1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' listBoxDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected listBoxDataSource As Global.DevExpress.Web.ASPxListBox

        ''' <summary>
        ''' LayoutItemNestedControlContainer2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' listBoxQuery control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected listBoxQuery As Global.DevExpress.Web.ASPxListBox

        ''' <summary>
        ''' LayoutItemNestedControlContainer3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' btDataSourceAdd control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btDataSourceAdd As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' LayoutItemNestedControlContainer4 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer4 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' btDataSourceEdit control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btDataSourceEdit As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' LayoutItemNestedControlContainer5 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer5 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' btDataSourceDelete control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btDataSourceDelete As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btQueryAdd control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btQueryAdd As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btQueryEdit control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btQueryEdit As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btQueryDelete control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btQueryDelete As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' LayoutItemNestedControlContainer6 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer6 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' lbWizardError control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lbWizardError As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' LayoutItemNestedControlContainer7 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LayoutItemNestedControlContainer7 As Global.DevExpress.Web.LayoutItemNestedControlContainer

        ''' <summary>
        ''' btApply control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btApply As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btCancel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btCancel As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' popupDataSourceEditor control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected popupDataSourceEditor As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' frmDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected frmDataSource As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' txDataSourceName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected txDataSourceName As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' cbDataSourceConnection control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected cbDataSourceConnection As Global.DevExpress.Web.ASPxComboBox

        ''' <summary>
        ''' lbDataSourceError control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lbDataSourceError As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' btDataSourceSave control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btDataSourceSave As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btDataSourceCancel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btDataSourceCancel As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' popupQueryEditor control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected popupQueryEditor As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' frmQuery control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected frmQuery As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' txQueryName control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected txQueryName As Global.DevExpress.Web.ASPxTextBox

        ''' <summary>
        ''' mmQuerySql control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected mmQuerySql As Global.DevExpress.Web.ASPxMemo

        ''' <summary>
        ''' lbQueryError control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lbQueryError As Global.DevExpress.Web.ASPxLabel

        ''' <summary>
        ''' btQuerySave control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btQuerySave As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' btQueryCancel control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected btQueryCancel As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
